# specify which database and adapter to use for which environment

development: #used by rake tasks, knows what database to use, defaults to development
  adapter: sqlite3
  database: db/film-file-development

test:
  adapter: sqlite3
  database: db/film-file-test

production:
  adapter: sqlite3
  database: db/film-file-production
